// Weather update

export const WEATHER_UPDATE_VIEW_INIT = "WEATHER_UPDATE_INIT";
export const WEATHER_UPDATE_VIEW_SUCCESS = "WEATHER_UPDATE_VIEW_SUCCESS";
export const WEATHER_UPDATE_VIEW_FAIL = "WEATHER_UPDATE_VIEW_FAIL";